export enum RouteNames {
    ON_BOARDING = "onboarding",
    MAIN = "main",
    LOCATIONS = "locations",
    TOURS = "tours",
    TOUR = "tour",
    CONTRIBUTOR = "contributor",
    PROFILE = "profile",
    FAVOURITES = "favourites",
    CREATE = "create",
    SETTINGS = "settings",
    WIP = "wip",
    SUCCESS = "success",
    BOOKING = "booking",
    AUTH = "auth",
    EDIT_PROFILE = "edit",
    NOT_FOUND = "404",
    LOGIN = "https://api.excopen.ru/oauth2/authorization/google",
}
