export enum TourFormatBehavior {
    WALK = "Пешком",
    BIKE = "Велосипед",
    SEGWAY = "Сегвей",
    SCOOTER = "Электросамокат",
    CAR = "Автомобиль",
    BUS = "Автобус",
    TRAM = "Трамвай",
    ATV = "Квадроцикл",
    HORSE = "Конная прогулка",
    BOAT = "Катер",
    KAYAK = "Каяк",
    SUBMARINE = "Подводная лодка",
    HELICOPTER = "Вертолет",
    BALLOON = "Воздушный шар",
    QUEST = "Квест",
    THEATRICAL = "Театрализованная экскурсия",
    GASTRONOMIC = "Гастрономическая экскурсия",
    VIRTUAL = "Виртуальная экскурсия"
}
